### ISSUE TITLE
Need to add a You are here: prefix to Home

### ISSUE THREAD

**Issue by stephcathoh** [x3p0-dev/x3p0-breadcrumbs#5]
I am not sure the best approach to add You are here: before Home in the breadcrumbs

**Comment by justintadlock** [comment]
You can add a Row block with a nested Paragraph and Breadcrumbs block:

![image](https://github.com/x3p0-dev/x3p0-breadcrumbs/assets/1816309/b11968f0-4dd5-4773-b7fd-23061374413a)

**Comment by stephcathoh** [comment]
Thank you.
